"""Download the latin subset of Nunito and emit a local @font-face stylesheet.

Nunito v32 on Google Fonts ships as a VARIABLE font: the same .woff2 file is
returned for every weight, covering 200-1000. So we keep exactly one file and
declare a weight range instead of four near-duplicates.

Chrome extension pages (MV3) cannot fetch remote fonts (default CSP blocks it),
so the font must live inside the extension folder.
"""
import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Ask for the variable axis explicitly.
CSS_URL = ("https://fonts.googleapis.com/css2?family=Nunito:wght@200..1000"
           "&display=swap")

req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
css = urllib.request.urlopen(req, timeout=30).read().decode("utf-8")

blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)

latin = None
for subset, block in blocks:
    if subset == "latin":
        latin = block
        break

if not latin:
    raise SystemExit("latin subset not found in the Google Fonts response")

url = re.search(r"url\((https://[^)]+)\)", latin).group(1)
urange = re.search(r"unicode-range:\s*([^;]+);", latin).group(1).strip()

fname = "nunito-latin-var.woff2"
fpath = os.path.join(HERE, fname)

req = urllib.request.Request(url, headers={"User-Agent": UA})
data = urllib.request.urlopen(req, timeout=30).read()
open(fpath, "wb").write(data)
print(f"downloaded {fname}: {len(data):,} bytes")

css_out = f"""/* Nunito — self-hosted, latin subset, variable weight 200-1000.
   Generated by build_fonts.py. Do not edit by hand.

   Nunito ships as a variable font, so one file covers every weight. */
@font-face {{
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 200 1000;
  font-display: swap;
  src: url('nunito-latin-var.woff2') format('woff2-variations'),
       url('nunito-latin-var.woff2') format('woff2');
  unicode-range: {urange};
}}
"""

open(os.path.join(HERE, "nunito-local.css"), "w", encoding="utf-8").write(css_out)
print("wrote nunito-local.css")
